# Generated by Django 4.2.16 on 2024-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронный адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Прикрепить файл')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку данных')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'Пользователи',
            },
        ),
    ]
